//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HRM_DBEntities : DbContext
    {
        public HRM_DBEntities()
            : base("name=HRM_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<M_CandidateMasters> M_CandidateMasters { get; set; }
        public virtual DbSet<M_CommonMasterTable> M_CommonMasterTable { get; set; }
        public virtual DbSet<M_CompanyMasters> M_CompanyMasters { get; set; }
        public virtual DbSet<M_DesignationMaster> M_DesignationMaster { get; set; }
        public virtual DbSet<M_EmployeeMasters> M_EmployeeMasters { get; set; }
        public virtual DbSet<M_FunctionAreaMaster> M_FunctionAreaMaster { get; set; }
        public virtual DbSet<M_IndustryMaster> M_IndustryMaster { get; set; }
        public virtual DbSet<M_LocationMasters> M_LocationMasters { get; set; }
        public virtual DbSet<M_RequirementMaster> M_RequirementMaster { get; set; }
        public virtual DbSet<M_RoleMaster> M_RoleMaster { get; set; }
        public virtual DbSet<T_CandidateFollowUpDetails> T_CandidateFollowUpDetails { get; set; }
        public virtual DbSet<T_FinalCandidatePlacementDetails> T_FinalCandidatePlacementDetails { get; set; }
        public virtual DbSet<M_NavigationMaster> M_NavigationMaster { get; set; }
        public virtual DbSet<M_ProjectMaster> M_ProjectMaster { get; set; }
        public virtual DbSet<T_EmployeeAttendance> T_EmployeeAttendance { get; set; }
        public virtual DbSet<T_EmployeeLeave> T_EmployeeLeave { get; set; }
        public virtual DbSet<T_EmployeeTimeSheetTable> T_EmployeeTimeSheetTable { get; set; }
        public virtual DbSet<T_EmployeeDocument> T_EmployeeDocument { get; set; }
        public virtual DbSet<M_EmployeeSalaryMaster> M_EmployeeSalaryMaster { get; set; }
        public virtual DbSet<T_TimeSeatMaster> T_TimeSeatMaster { get; set; }
    }
}
