//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_DesignationMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_DesignationMaster()
        {
            this.M_EmployeeMasters = new HashSet<M_EmployeeMasters>();
        }
    
        public int DesignationID { get; set; }
        public string Designation { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_EmployeeMasters> M_EmployeeMasters { get; set; }
    }
}
