//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EmployeeSalaryMaster
    {
        public int SalaryID { get; set; }
        public string EmployeeID { get; set; }
        public int SalaryTypeID { get; set; }
        public int Basic { get; set; }
        public int DA { get; set; }
        public int HRA { get; set; }
        public int SPECIAL_ALLOWANCE { get; set; }
        public int AWARDS { get; set; }
        public int MEDICAL_ALLOWANCE { get; set; }
        public int GROSS_EARNING { get; set; }
        public int GROSS_DEDUCTIONS { get; set; }
        public int NET_Pay { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        public virtual M_EmployeeMasters M_EmployeeMasters { get; set; }
    }
}
