//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_EmployeeMasters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_EmployeeMasters()
        {
            this.M_EmployeeMasters1 = new HashSet<M_EmployeeMasters>();
            this.T_EmployeeAttendance = new HashSet<T_EmployeeAttendance>();
            this.T_EmployeeLeave = new HashSet<T_EmployeeLeave>();
            this.T_EmployeeLeave1 = new HashSet<T_EmployeeLeave>();
            this.T_EmployeeTimeSheetTable = new HashSet<T_EmployeeTimeSheetTable>();
            this.T_EmployeeDocument = new HashSet<T_EmployeeDocument>();
            this.M_EmployeeSalaryMaster = new HashSet<M_EmployeeSalaryMaster>();
            this.T_TimeSeatMaster = new HashSet<T_TimeSeatMaster>();
        }
    
        public string EmployeeID { get; set; }
        public string EmployeeName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int CountryID { get; set; }
        public string PersonalEmailID { get; set; }
        public string CEmailID { get; set; }
        public string ContactNo { get; set; }
        public string EmergencyContactNo { get; set; }
        public int GenderID { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string Department { get; set; }
        public int DesignationID { get; set; }
        public string ManagerID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
        public string EmployeePic { get; set; }
        public string Pwd { get; set; }
    
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        public virtual M_CommonMasterTable M_CommonMasterTable1 { get; set; }
        public virtual M_DesignationMaster M_DesignationMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_EmployeeMasters> M_EmployeeMasters1 { get; set; }
        public virtual M_EmployeeMasters M_EmployeeMasters2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EmployeeAttendance> T_EmployeeAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EmployeeLeave> T_EmployeeLeave { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EmployeeLeave> T_EmployeeLeave1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EmployeeTimeSheetTable> T_EmployeeTimeSheetTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_EmployeeDocument> T_EmployeeDocument { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_EmployeeSalaryMaster> M_EmployeeSalaryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_TimeSeatMaster> T_TimeSeatMaster { get; set; }
    }
}
