//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class M_LocationMasters
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public M_LocationMasters()
        {
            this.M_CandidateMasters = new HashSet<M_CandidateMasters>();
            this.M_CompanyMasters = new HashSet<M_CompanyMasters>();
            this.M_RequirementMaster = new HashSet<M_RequirementMaster>();
        }
    
        public int LocationID { get; set; }
        public int CountryID { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Description { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CandidateMasters> M_CandidateMasters { get; set; }
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_CompanyMasters> M_CompanyMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<M_RequirementMaster> M_RequirementMaster { get; set; }
    }
}
