//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_EmployeeTimeSheetTable
    {
        public int TimeSheetID { get; set; }
        public string EmployeeID { get; set; }
        public int ProjectID { get; set; }
        public Nullable<int> TypeOfWorkID { get; set; }
        public System.DateTime WorkDate { get; set; }
        public int WorkingHours { get; set; }
        public string WorkDescription { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        public virtual M_EmployeeMasters M_EmployeeMasters { get; set; }
        public virtual M_ProjectMaster M_ProjectMaster { get; set; }
    }
}
