//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_FinalCandidatePlacementDetails
    {
        public int FinalEmployeeID { get; set; }
        public string CandidateID { get; set; }
        public int CompanyID { get; set; }
        public int EmployeeTypeID { get; set; }
        public Nullable<int> CTCOfferToCandidate { get; set; }
        public Nullable<int> CTCOfferByCompany { get; set; }
        public System.DateTime DateOfJoining { get; set; }
        public string LastWorkingDate { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_CandidateMasters M_CandidateMasters { get; set; }
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        public virtual M_CompanyMasters M_CompanyMasters { get; set; }
    }
}
