//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HRMWeb.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_TimeSeatMaster
    {
        public int TimesheatID { get; set; }
        public string EmployeeID { get; set; }
        public int ProjectID { get; set; }
        public System.DateTime WeekStarting { get; set; }
        public int TimeCardPeriodInDays { get; set; }
        public string Comments { get; set; }
        public int LeaveTypeID { get; set; }
        public Nullable<int> BillingTypeID { get; set; }
        public Nullable<double> Day1 { get; set; }
        public Nullable<double> Day2 { get; set; }
        public Nullable<double> Day3 { get; set; }
        public Nullable<double> Day4 { get; set; }
        public Nullable<double> Day5 { get; set; }
        public Nullable<double> Day6 { get; set; }
        public Nullable<double> Day7 { get; set; }
        public double TotalWorkingHours { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedDate { get; set; }
        public bool Active { get; set; }
    
        public virtual M_CommonMasterTable M_CommonMasterTable { get; set; }
        public virtual M_CommonMasterTable M_CommonMasterTable1 { get; set; }
        public virtual M_EmployeeMasters M_EmployeeMasters { get; set; }
        public virtual M_ProjectMaster M_ProjectMaster { get; set; }
    }
}
